version: "3.2"
services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "15432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  pastex:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    command:
      - ./bin/run.sh
